# Generated by Django 4.2.29 on 2026-03-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '已取消'), (1, '等待中'), (2, '已到馆'), (3, '已完成'), (4, '已过期')], db_index=True, default=1, verbose_name='状态')),
                ('reserved_at', models.DateTimeField(auto_now_add=True, verbose_name='预约时间')),
                ('expire_at', models.DateTimeField(verbose_name='预约到期时间')),
                ('notify_at', models.DateTimeField(blank=True, null=True, verbose_name='到馆通知时间')),
                ('cancel_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='books.book', verbose_name='预约图书')),
            ],
            options={
                'verbose_name': '预约记录',
                'verbose_name_plural': '预约记录',
                'db_table': 'reservations',
                'ordering': ['-reserved_at'],
            },
        ),
    ]
