# Generated by Django 4.2.29 on 2026-03-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='罚款金额')),
                ('reason', models.CharField(default='逾期还书', max_length=100, verbose_name='原因')),
                ('status', models.SmallIntegerField(choices=[(0, '待缴'), (1, '已缴'), (2, '已免除')], db_index=True, default=0, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='缴清时间')),
                ('borrow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='borrows.borrow', verbose_name='关联借阅')),
            ],
            options={
                'verbose_name': '罚款记录',
                'verbose_name_plural': '罚款记录',
                'db_table': 'fines',
                'ordering': ['-created_at'],
            },
        ),
    ]
