# Generated by Django 4.2.29 on 2026-03-21 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fines', to=settings.AUTH_USER_MODEL, verbose_name='欠款用户'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['user', 'status'], name='fines_user_id_7da2b3_idx'),
        ),
    ]
