# Generated by Django 4.2.29 on 2026-03-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(help_text='登录用户名', max_length=50, unique=True, verbose_name='用户名')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('role', models.SmallIntegerField(choices=[(0, '读者'), (1, '管理员'), (2, '超级管理员')], db_index=True, default=0, verbose_name='角色')),
                ('status', models.SmallIntegerField(choices=[(0, '禁用'), (1, '正常')], db_index=True, default=1, verbose_name='状态')),
                ('avatar_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='头像地址')),
                ('is_staff', models.BooleanField(default=False, help_text='是否可以登录 admin 后台', verbose_name='staff status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
