# Generated by Django 4.2.29 on 2026-03-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='书名')),
                ('author', models.CharField(max_length=255, verbose_name='作者')),
                ('publisher', models.CharField(blank=True, max_length=100, null=True, verbose_name='出版社')),
                ('cover_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='封面图片')),
                ('description', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('total_copies', models.PositiveIntegerField(default=0, verbose_name='馆藏总册数')),
                ('available_copies', models.PositiveIntegerField(default=0, help_text='冗余字段，事务维护', verbose_name='可借册数')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='定价')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='出版日期')),
                ('language', models.CharField(default='zh', max_length=20, verbose_name='语言')),
                ('status', models.SmallIntegerField(choices=[(0, '下架'), (1, '上架')], db_index=True, default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'db_table': 'books',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('code', models.CharField(blank=True, help_text='如 TP312', max_length=20, null=True, unique=True, verbose_name='分类编号')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='越小越靠前', verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '图书分类',
                'verbose_name_plural': '图书分类',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='条形码')),
                ('condition', models.SmallIntegerField(choices=[(1, '全新'), (2, '良好'), (3, '一般'), (4, '破损')], default=1, verbose_name='品相')),
                ('status', models.SmallIntegerField(choices=[(0, '注销'), (1, '在馆'), (2, '借出'), (3, '预约锁定'), (4, '丢失')], db_index=True, default=1, verbose_name='状态')),
                ('location', models.CharField(blank=True, help_text='如 A区-03-2', max_length=50, null=True, verbose_name='书架位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='books.book', verbose_name='所属图书')),
            ],
            options={
                'verbose_name': '图书副本',
                'verbose_name_plural': '图书副本',
                'db_table': 'book_copies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.category', verbose_name='分类'),
        ),
    ]
