# Generated by Django 4.2.29 on 2026-03-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_at', models.DateTimeField(auto_now_add=True, verbose_name='借出时间')),
                ('due_at', models.DateTimeField(db_index=True, verbose_name='应还时间')),
                ('return_at', models.DateTimeField(blank=True, null=True, verbose_name='实际归还时间')),
                ('status', models.SmallIntegerField(choices=[(0, '已还'), (1, '借阅中'), (2, '逾期'), (3, '丢失')], db_index=True, default=1, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('book', models.ForeignKey(help_text='冗余字段，方便统计查询', on_delete=django.db.models.deletion.PROTECT, related_name='borrows', to='books.book', verbose_name='图书')),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrows', to='books.bookcopy', verbose_name='借出副本')),
            ],
            options={
                'verbose_name': '借阅记录',
                'verbose_name_plural': '借阅记录',
                'db_table': 'borrows',
                'ordering': ['-borrow_at'],
            },
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewed_at', models.DateTimeField(auto_now_add=True, verbose_name='续借时间')),
                ('new_due_at', models.DateTimeField(verbose_name='续借后应还时间')),
                ('borrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='borrows.borrow', verbose_name='借阅记录')),
            ],
            options={
                'verbose_name': '续借记录',
                'verbose_name_plural': '续借记录',
                'db_table': 'renewals',
                'ordering': ['-renewed_at'],
            },
        ),
    ]
