# Generated by Django 4.2.29 on 2026-03-21 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_borrows', to=settings.AUTH_USER_MODEL, verbose_name='经手管理员'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrows', to=settings.AUTH_USER_MODEL, verbose_name='借阅用户'),
        ),
        migrations.AddIndex(
            model_name='borrow',
            index=models.Index(fields=['user', 'status'], name='borrows_user_id_594b88_idx'),
        ),
        migrations.AddIndex(
            model_name='borrow',
            index=models.Index(fields=['book_copy', 'status'], name='borrows_book_co_02eba1_idx'),
        ),
    ]
