# Generated by Django 4.2.29 on 2026-03-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(help_text='支持 HTML', verbose_name='内容')),
                ('status', models.SmallIntegerField(choices=[(0, '草稿'), (1, '已发布'), (2, '已下架')], db_index=True, default=0, verbose_name='状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'db_table': 'announcements',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
